import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Footer} from "@/app/components/footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// Using Lexend Exa font
const lexendExa = {
    variable: "--font-lexend-exa",
    subsets: ["latin"],
};

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="h-full">
        <head>
            {/* Adding Lexend Exa */}
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/>
            <link
                href="https://fonts.googleapis.com/css2?family=Lexend+Exa:wght@100..900&display=swap"
                rel="stylesheet"
            />
        </head>
        <body
            className={`${geistSans.variable} ${geistMono.variable} ${lexendExa.variable} antialiased h-full flex flex-col`}
        >
        <div className="flex-1">
            {children}
        </div>
        <Footer/>
        </body>
        </html>
    );
}
